### ISSUE TITLE
关于中文Aspect-Opinion的抽取

### ISSUE THREAD

**Issue by nxznm** [l294265421/ASMOTE#2]
打扰了！想请教下博主，关于aspect-opinion pair的抽取或者是aspect-opinion-sentiment三元组的抽取有啥中文数据集吗？目前找了一圈，发现给定一些固定的category然后预测极性，或者是抽取aspect并给出极性这样的中文数据集比较多，而同时涉及到aspect和opinion抽取的中文数据集没咋注意到过。

**Comment by l294265421** [comment]
> 打扰了！想请教下博主，关于aspect-opinion pair的抽取或者是aspect-opinion-sentiment三元组的抽取有啥中文数据集吗？目前找了一圈，发现给定一些固定的category然后预测极性，或者是抽取aspect并给出极性这样的中文数据集比较多，而同时涉及到aspect和opinion抽取的中文数据集没咋注意到过。

我也没看到过中文aspect-opinion pair抽取数据集

**Comment by nxznm** [comment]
好的，感谢回复！
